pipeline {
    agent any
    stages {
        stage('Pull code') {
            steps {
                checkout scm
            }
        }
        stage('Download dependencies') {
            steps {
                dir('frontend') {
                    sh 'yarn install'
                }
            }
        }
        stage('Scan & auto fixed code') {
            steps {
                dir('frontend') {
                    sh 'yarn lint'
                }
            }
        }
        stage('Unit Test') {
            steps {
                dir('frontend') {
                    sh 'yarn unit'
                }
                publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: './frontend', reportFiles: 'test-report.html', reportName: 'Unit Test Report', reportTitles: 'Unit Test Report'])
            }
        }
        stage('Unit Test Coverage') {
            steps {
                dir('frontend') {
                    sh 'yarn unit:coverage'
                }
                publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: './frontend/coverage/lcov-report', reportFiles: 'index.html', reportName: 'Unit Test Coverage Report', reportTitles: 'Unit Test Coverage Report'])
            }
        }
        stage('Component Test') {
            steps {
                dir('frontend') {
                    sh "yarn component"
                }
                publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: './frontend', reportFiles: 'test-report.html', reportName: 'Component Test Report', reportTitles: 'Component Test Report'])
            }
        }
        stage('Component Test Coverage') {
            steps {
                dir('frontend') {
                    sh 'yarn component:coverage'
                }
                publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: './frontend/coverage/lcov-report', reportFiles: 'index.html', reportName: 'Component Test Coverage Report', reportTitles: 'Component Test Coverage Report'])
            }
        }
        stage('E2E Test') {
            steps {
                dir('frontend') {
                    sh "yarn e2e"
                }
            }
        }
        stage('Build') {
            steps {
                dir('frontend') {
                    sh "yarn build"
                }
            }
        }
    }
}