pipeline {
    agent any
    stages {
	stage('Pull code') {
            steps {
                checkout scm
            }
        }
	stage('Download dependencies') {
            steps {
                dir('backend-demo-test') {
                    sh 'yarn'
                }
            }
        }
        stage('Build') {
            steps {
                dir('backend-demo-test') {
                    sh 'yarn build'
                }
            }
        }
        stage('Unit Test') {
            steps {
                dir('backend-demo-test') {
                    sh 'yarn test:unit'
                }
            }
        }
        stage('Unit Test Coverage') {
            steps {
                dir('backend-demo-test') {
                    sh 'yarn test:unit:coverage'
                }
            }
        }
		stage('Component Test') {
            steps {
                dir('backend-demo-test') {
                    sh 'yarn test:component'
                }
            }
        }
        stage('Component Test Coverage') {
            steps {
                dir('backend-demo-test') {
                    sh 'yarn test:component:coverage'
                }
            }
        }
        stage('E2E Test') {
            steps {
                dir('backend-demo-test') {
                    sh "yarn test:e2e"
                }
            }
        }
    }
}
