pipeline {
    agent any
    stages {
	stage('Pull code') {
            steps {
                checkout scm
            }
        }
	stage('Download dependencies') {
            steps {
                dir('backend-demo-test') {
                    sh 'yarn'
                }
            }
        }
        stage('Build') {
            steps {
                dir('backend-demo-test') {
                    sh 'yarn build'
                }
            }
        }
        stage('Unit Test') {
            steps {
                dir('backend-demo-test') {
                    sh 'yarn test:unit'
                }
            }
        }
        stage('Unit Test Coverage') {
            steps {
                dir('backend-demo-test') {
                    sh 'yarn test:unit:coverage'
                }
            }
        }
        stage('Create Unit Test Report') {
            steps {
                dir('backend-demo-test') {
                    sh 'yarn test:unit &> unit.txt'
                    sh 'Get-Content unit.txt | Set-Content -Encoding utf8 unit.txt'
                    publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: './', reportFiles: 'unit.txt', reportName: 'Unit Test Report', reportTitles: 'Unit Test Report'])
                }
            }
        }
        stage('Create Unit Test Coverage Report') {
            steps {
                dir('backend-demo-test') {
                    sh 'yarn test:unit:coverage &> unit-coverage.txt'
                    publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: './', reportFiles: 'unit-coverage.txt', reportName: 'Unit Test Report', reportTitles: 'Unit Test Report'])
                }
            }
        }
		stage('Component Test') {
            steps {
                dir('backend-demo-test') {
                    sh 'yarn test:component'
                }
            }
        }
        stage('Component Test Coverage') {
            steps {
                dir('backend-demo-test') {
                    sh 'yarn test:component:coverage'
                }
            }
        }
        stage('Create Component Test Report') {
            steps {
                dir('backend-demo-test') {
                    sh 'yarn test:component &> component.txt'
                    publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: './', reportFiles: 'component.txt', reportName: 'Component Test Report', reportTitles: 'Component Test Report'])
                }
            }
        }
        stage('Create Component Test Coverage Report') {
            steps {
                dir('backend-demo-test') {
                    sh 'yarn test:component:coverage &> component-coverage.txt'
                    publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: './', reportFiles: 'component-coverage.txt', reportName: 'Component Test Coverage Report', reportTitles: 'Component Test Coverage Report'])
                }
            }
        }
        stage('E2E Test') {
            steps {
                dir('backend-demo-test') {
                    sh "yarn test:e2e"
                }
            }
        }
    }
}
