pipeline {
    agent any
    stages {
	   stage('Pull code') {
            steps {
                checkout scm
            }
        }
	stage('Download dependencies') {
            steps {
                dir('frontend-demo-test') {
                    sh 'yarn'
                }
            }
        }
        stage('Scan & auto fixed code') {
            steps {
                dir('frontend-demo-test') {
                    sh 'yarn lint'
                }
            }
        }
        stage('Unit Test') {
            steps {
                dir('frontend-demo-test') {
                    sh 'yarn unit'
                }
            }
        }
		stage('Unit Test Coverage') {
            steps {
                dir('frontend-demo-test') {
                    sh 'yarn unit:coverage'
                }
            }
        }
        stage('Create Unit Test Report') {
            steps {
                dir('frontend-demo-test') {
                    sh 'yarn unit 2> unit.txt'
                    publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: './', reportFiles: 'unit.txt', reportName: 'Unit Test Report', reportTitles: 'Unit Test Report'])
                }
            }
        }
        stage('Create Unit Test Coverage Report') {
            steps {
                publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: './frontend-demo-test/coverage/lcov-report', reportFiles: 'index.html', reportName: 'Unit Test Coverage Report', reportTitles: 'Unit Test Coverage Report'])
            }
        }
        stage('Component Test') {
            steps {
                dir('frontend-demo-test') {
                    sh "yarn component"
                }
            }
        }
        stage('Create Component Test&Coverage Report') {
            steps {
                dir('frontend-demo-test') {
                    publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: './', reportFiles: 'component.html', reportName: 'Component Test&Coverage Report', reportTitles: 'Component Test&Coverage Report'])
                }
            }
        }
        stage('E2E Test') {
            steps {
                dir('frontend-demo-test') {
                    sh "yarn e2e"
                }
            }
        }
        stage('Build') {
            steps { 
                dir('frontend-demo-test') {
                    sh "yarn build"
                }
            }
        }
    }
}
